version: "3"
services:
    website:
        image: anax/dev:latest-apache
        ports:
            - "18081:80"
        volumes:
            - .:/app
            - ./config/docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
